/**
 * Generates the NSIS scripts.
 *
 * Everything a product would otherwise hardcode into a hand-written .nsi is a
 * parameter here. Two details are load-bearing and easy to lose:
 *
 *  - Every plugin call carries /NOUNLOAD. Without it NSIS calls FreeLibrary the
 *    moment a call returns, which discards the ability registry, the config
 *    store and the window.
 *  - Scripts are emitted as UTF-8 *with BOM*. NSIS 3 otherwise reads them in
 *    the system ANSI code page and rejects any non-ASCII byte, which a Chinese
 *    or accented product name will always contain.
 */
import type { ResolvedConfig } from './config.js';
import { normalizeVersion } from './config.js';

/**
 * Escapes a literal string for NSIS.
 *
 * `$` starts a variable reference in NSIS, so a filesystem path containing one
 * has to be doubled or the compiler silently substitutes something else. (In a
 * JavaScript replacement string `$$$$` produces two dollar signs, which is the
 * NSIS escape for one.)
 */
function nsisString(value: string): string {
  return value.replace(/\$/g, '$$$$').replace(/"/g, '$\\"').replace(/\r?\n/g, '$\\n');
}

/**
 * For fields documented to accept NSIS variables — `install.defaultDir` is the
 * one — where `$PROGRAMFILES` and friends must survive to be expanded.
 *
 * Escaping these was a real bug: `$LOCALAPPDATA\App` became the literal string
 * `$LOCALAPPDATA\App`, and the installer cheerfully offered to install into a
 * directory of that name.
 */
function nsisExpandable(value: string): string {
  return value.replace(/"/g, '$\\"').replace(/\r?\n/g, '$\\n');
}

/** Values placed inside !define. */
function defineValue(value: string): string {
  return value.replace(/\$/g, '$$$$').replace(/"/g, '$\\"');
}

/** Where the installer parks the renderer for the uninstaller to reuse. */
export const UNINSTALL_RUNTIME_DIR = 'blink-runtime';

export interface NsiInputs {
  config: ResolvedConfig;
  /** Absolute path to the staged single-file page. */
  htmlPath: string;
  /** Absolute path to the staged uninstaller page, when that UI is enabled. */
  uninstallHtmlPath?: string;
  /** Absolute path to the miniblink DLL. */
  miniblinkPath: string;
  /** Absolute directory containing blinkkit.dll, for !addplugindir. */
  pluginDir: string;
  /** Absolute path to the staged application payload. */
  sourceDir: string;
  /** Absolute output path for the produced installer. */
  outputPath: string;
  /** Absolute path to the icon, if one was resolved. */
  iconPath?: string;
  /** Contents of the user's custom .nsh, already read. */
  includeSnippet?: string;
}

export function renderInstallerScript(inputs: NsiInputs): string {
  const { config: c } = inputs;
  const version4 = normalizeVersion(c.version);
  const registryKey =
    c.install.registryKey ??
    `Software\\${c.publisher || c.productName}\\${c.productName}`;
  const startMenuFolder = c.install.shortcuts.startMenuFolder ?? c.productName;
  const uninstallKey = `Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${c.appId}`;

  const defines = Object.entries(c.nsis.defines)
    .map(([key, value]) => `!define ${key} "${defineValue(value)}"`)
    .join('\n');

  // A per-user install cannot write HKLM or the all-users start menu, and
  // failing to notice leaves an app with no Programs-and-Features entry and no
  // working uninstaller. Follow the elevation setting everywhere.
  const regRoot = c.install.elevate ? 'HKLM' : 'HKCU';
  const shellContext = c.install.elevate ? 'all' : 'current';

  return `; Generated by blink-installer. Do not edit; edit your config instead.
Unicode true
ManifestDPIAware true

!define PRODUCT_NAME "${defineValue(c.productName)}"
!define PRODUCT_VERSION "${version4}"
!define PRODUCT_PUBLISHER "${defineValue(c.publisher)}"
!define PRODUCT_DESCRIPTION "${defineValue(c.description)}"
!define PRODUCT_WEBSITE "${defineValue(c.website)}"
!define PRODUCT_EXE "${defineValue(c.exe)}"
!define REGISTRY_KEY "${defineValue(registryKey)}"
!define UNINSTALL_KEY "${defineValue(uninstallKey)}"
!define START_MENU_FOLDER "${defineValue(startMenuFolder)}"
${defines}

!include "LogicLib.nsh"
!include "FileFunc.nsh"
; \${Silent} and the other run-mode checks.
!include "Sections.nsh"
; Defines \${SW_HIDE}. Without it NSIS silently substitutes an empty string and
; its own installer frame stays visible behind the page.
!include "WinMessages.nsh"

Name "\${PRODUCT_NAME} \${PRODUCT_VERSION}"
OutFile "${nsisString(inputs.outputPath)}"
InstallDir "${nsisExpandable(c.install.defaultDir)}"
RequestExecutionLevel ${c.install.elevate ? 'admin' : 'user'}
SetCompressor /SOLID ${c.compression}
; UninstallIcon as well as Icon: without it the uninstaller keeps the stock
; NSIS icon, and since the plugin gives a window the icon of the executable it
; is running inside, the uninstaller's taskbar button would show that instead
; of the product's.
${inputs.iconPath ? `Icon "${nsisString(inputs.iconPath)}"\nUninstallIcon "${nsisString(inputs.iconPath)}"` : ''}

; The stub's own window is never shown — the page is the entire UI.
SilentInstall normal
ShowInstDetails nevershow
AutoCloseWindow true
XPStyle on

VIProductVersion "\${PRODUCT_VERSION}"
VIAddVersionKey "ProductName" "\${PRODUCT_NAME}"
VIAddVersionKey "ProductVersion" "\${PRODUCT_VERSION}"
VIAddVersionKey "FileVersion" "\${PRODUCT_VERSION}"
VIAddVersionKey "CompanyName" "\${PRODUCT_PUBLISHER}"
VIAddVersionKey "FileDescription" "\${PRODUCT_DESCRIPTION}"
VIAddVersionKey "LegalCopyright" "${defineValue(c.copyright)}"

!addplugindir /x86-unicode "${nsisString(inputs.pluginDir)}"

Var StartedInstall
Var UnStarted
Var UnHasUi

; ---------------------------------------------------------------------------
; Pages
;
; 1. Custom page: the installer UI runs its own message loop here. It returns
;    when the page calls installer.next().
; 2. instfiles: NSIS copies files. Its dialog stays hidden; the page keeps
;    rendering because NSIS pumps messages for this thread while the Section
;    runs on a worker.
; 3. Custom page: the completion screen, again on our own loop.
; ---------------------------------------------------------------------------
Page custom PageUi
Page instfiles "" PageInstallPre
Page custom PageDone

Function .onInit
  InitPluginsDir

  ; The UI runtime.
  File \`/oname=$PLUGINSDIR\\node.dll\` "${nsisString(inputs.miniblinkPath)}"
  File \`/oname=$PLUGINSDIR\\index.min.html\` "${nsisString(inputs.htmlPath)}"

${
  c.install.elevate
    ? `  UserInfo::GetAccountType
  Pop $0
  \${If} $0 != "admin"
    MessageBox MB_ICONSTOP "\${PRODUCT_NAME} must be installed by an administrator.$\\r$\\nRight-click Setup and choose Run as administrator."
    SetErrorLevel 740 ; ERROR_ELEVATION_REQUIRED
    Quit
  \${EndIf}
`
    : ''
}
  StrCpy $StartedInstall "0"

  blinkkit::SetRegistryKey /NOUNLOAD "${regRoot}" "\${REGISTRY_KEY}"

  ; Everything the page might want to render, pushed in before it loads.
  blinkkit::SetConfig /NOUNLOAD "productName" "\${PRODUCT_NAME}"
  blinkkit::SetConfig /NOUNLOAD "version" "\${PRODUCT_VERSION}"
  blinkkit::SetConfig /NOUNLOAD "publisher" "\${PRODUCT_PUBLISHER}"
  blinkkit::SetConfig /NOUNLOAD "description" "\${PRODUCT_DESCRIPTION}"
  blinkkit::SetConfig /NOUNLOAD "website" "\${PRODUCT_WEBSITE}"
  blinkkit::SetConfig /NOUNLOAD "exeName" "\${PRODUCT_EXE}"
  blinkkit::SetConfig /NOUNLOAD "installDir" "$INSTDIR"
  blinkkit::SetConfig /NOUNLOAD "allowDirChange" "${c.install.allowDirChange ? '1' : '0'}"
  blinkkit::SetConfig /NOUNLOAD "mode" "install"
  blinkkit::SetConfig /NOUNLOAD "splash" "${c.splash.enabled ? '1' : '0'}"
  blinkkit::SetConfig /NOUNLOAD "splashDebug" "${process.env.BLINK_SPLASH_DEBUG === '1' ? '1' : '0'}"
  blinkkit::SetConfig /NOUNLOAD "splashTimeoutMs" "${c.splash.timeoutMs}"
  blinkkit::SetConfig /NOUNLOAD "windowWidth" "${c.window.width}"
  blinkkit::SetConfig /NOUNLOAD "windowHeight" "${c.window.height}"

  ; NSIS's resolved folder locations, so the page can show real paths.
  blinkkit::SetConfig /NOUNLOAD "sys.programFiles" "$PROGRAMFILES"
  blinkkit::SetConfig /NOUNLOAD "sys.localAppData" "$LOCALAPPDATA"
  blinkkit::SetConfig /NOUNLOAD "sys.appData" "$APPDATA"
  blinkkit::SetConfig /NOUNLOAD "sys.desktop" "$DESKTOP"
  blinkkit::SetConfig /NOUNLOAD "sys.startMenu" "$SMPROGRAMS"
  blinkkit::SetConfig /NOUNLOAD "sys.temp" "$TEMP"
  blinkkit::SetConfig /NOUNLOAD "sys.windir" "$WINDIR"

  ; Script functions the page may invoke by name.
  GetFunctionAddress $0 AbilityBeginInstall
  blinkkit::RegisterAbility /NOUNLOAD "beginInstall" $0
  GetFunctionAddress $0 AbilityCancel
  blinkkit::RegisterAbility /NOUNLOAD "cancel" $0
  GetFunctionAddress $0 AbilityLaunchApp
  blinkkit::RegisterAbility /NOUNLOAD "launchApp" $0
FunctionEnd

Function PageUi
  ; /S — silent install. Enterprises deploy this way and expect it to work, and
  ; it is the only way to install without a human at the keyboard. Skip the UI
  ; entirely and let the Section run against the default directory.
  \${If} \${Silent}
    StrCpy $StartedInstall "1"
    Return
  \${EndIf}

  ; Keep NSIS's own frame out of sight; our window is the whole UI.
  ShowWindow $HWNDPARENT \${SW_HIDE}

  ; The fifth argument opens the window covering the work area, for the splash.
  ; It has to be decided here rather than resized later: a layered window shows
  ; its initial size for a frame, and at these dimensions that reads as a flash.
  blinkkit::InitWindow /NOUNLOAD "$PLUGINSDIR" "\${PRODUCT_NAME}" "${c.window.width}" "${c.window.height}" "${c.splash.enabled ? '1' : '0'}"
  Pop $0
  \${If} $0 != "ok"
    MessageBox MB_ICONSTOP "The installer interface failed to start.$\\r$\\n$0"
    Quit
  \${EndIf}

  ; Blocks until the page calls installer.next().
  blinkkit::ShowPage /NOUNLOAD

  ; The page closed the window instead of proceeding: nothing was installed.
  \${If} $StartedInstall != "1"
    Quit
  \${EndIf}
FunctionEnd

Function AbilityBeginInstall
  ; Read back whatever directory the page settled on.
  blinkkit::GetConfig /NOUNLOAD "installDir"
  Pop $0
  \${If} $0 != ""
    StrCpy $INSTDIR $0
  \${EndIf}
  StrCpy $StartedInstall "1"
FunctionEnd

Function AbilityCancel
  Quit
FunctionEnd

Function AbilityLaunchApp
  ; ExecShell from the installer would inherit the elevated token; using the
  ; explorer trick keeps the app running as the logged-on user instead.
  Exec '"$WINDIR\\explorer.exe" "$INSTDIR\\\${PRODUCT_EXE}"'
FunctionEnd

Function PageInstallPre
  \${If} \${Silent}
    Return
  \${EndIf}
  ShowWindow $HWNDPARENT \${SW_HIDE}
  blinkkit::SetConfig /NOUNLOAD "mode" "installing"
  ; Start mirroring NSIS's progress bar and detail log into the page.
  blinkkit::BindProgress /NOUNLOAD
FunctionEnd

Section "Install"
  SetShellVarContext ${shellContext}
  SetOutPath "$INSTDIR"
  SetOverwrite try

  File /r "${nsisString(inputs.sourceDir)}\\*.*"

${
  c.install.uninstallEntry && c.uninstall.ui && inputs.uninstallHtmlPath
    ? `  ; Park a renderer for the uninstaller. It is copied out of $PLUGINSDIR
  ; rather than embedded a second time: the uninstaller lives inside this
  ; installer, so a second copy would double the download for every user.
  CreateDirectory "$INSTDIR\\${UNINSTALL_RUNTIME_DIR}"
  CopyFiles /SILENT "$PLUGINSDIR\\node.dll" "$INSTDIR\\${UNINSTALL_RUNTIME_DIR}\\node.dll"
`
    : ''
}${
  c.install.uninstallEntry
    ? `  WriteUninstaller "$INSTDIR\\Uninstall.exe"

  \${GetSize} "$INSTDIR" "/S=0K" $0 $1 $2
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "DisplayName" "\${PRODUCT_NAME}"
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "DisplayVersion" "\${PRODUCT_VERSION}"
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "Publisher" "\${PRODUCT_PUBLISHER}"
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "InstallLocation" "$INSTDIR"
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "DisplayIcon" "$INSTDIR\\\${PRODUCT_EXE}"
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "UninstallString" "$\\"$INSTDIR\\Uninstall.exe$\\""
  WriteRegStr ${regRoot} "\${UNINSTALL_KEY}" "QuietUninstallString" "$\\"$INSTDIR\\Uninstall.exe$\\" /S"
  WriteRegDWORD ${regRoot} "\${UNINSTALL_KEY}" "NoModify" 1
  WriteRegDWORD ${regRoot} "\${UNINSTALL_KEY}" "NoRepair" 1
  WriteRegDWORD ${regRoot} "\${UNINSTALL_KEY}" "EstimatedSize" "$0"
`
    : ''
}
${
  c.install.shortcuts.startMenu
    ? `  CreateDirectory "$SMPROGRAMS\\\${START_MENU_FOLDER}"
  CreateShortCut "$SMPROGRAMS\\\${START_MENU_FOLDER}\\\${PRODUCT_NAME}.lnk" "$INSTDIR\\\${PRODUCT_EXE}"
`
    : ''
}
${
  c.install.shortcuts.desktop
    ? `  CreateShortCut "$DESKTOP\\\${PRODUCT_NAME}.lnk" "$INSTDIR\\\${PRODUCT_EXE}"
`
    : ''
}
  WriteRegStr ${regRoot} "\${REGISTRY_KEY}" "InstallDir" "$INSTDIR"
  WriteRegStr ${regRoot} "\${REGISTRY_KEY}" "Version" "\${PRODUCT_VERSION}"
SectionEnd

Function PageDone
  \${If} \${Silent}
    Return
  \${EndIf}
  blinkkit::SetConfig /NOUNLOAD "mode" "done"
  blinkkit::SetConfig /NOUNLOAD "installDir" "$INSTDIR"
  ; Runs our loop again for the completion screen; returns when the page
  ; closes the window for real.
  blinkkit::ShowPage /NOUNLOAD
FunctionEnd

${inputs.includeSnippet ? `; ---- user include ----\n${inputs.includeSnippet}\n` : ''}
`;
}

export function renderUninstallerScript(inputs: NsiInputs): string {
  const { config: c } = inputs;
  const startMenuFolder = c.install.shortcuts.startMenuFolder ?? c.productName;
  const uninstallKey = `Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${c.appId}`;
  const registryKey =
    c.install.registryKey ??
    `Software\\${c.publisher || c.productName}\\${c.productName}`;

  // Must mirror the install side: a per-user install put its shortcuts and
  // registry entries in the current-user locations, and looking for them under
  // the all-users ones would leave them behind.
  const regRoot = c.install.elevate ? 'HKLM' : 'HKCU';
  const shellContext = c.install.elevate ? 'all' : 'current';
  const withUi = c.uninstall.ui && Boolean(inputs.uninstallHtmlPath);

  // Emitted as a section inside the installer script rather than a second
  // compilation: NSIS builds the uninstaller from the same script. Every
  // function here must be `un.`-prefixed — that is how NSIS knows it belongs
  // to the uninstaller rather than the installer.
  return `
; ===========================================================================
; Uninstaller
; ===========================================================================
${
  withUi
    ? `Function un.onInit
  InitPluginsDir

  ; The page is small enough to embed. The renderer is not, so the install
  ; left one behind for us; if it is missing (a hand-copied install, or an
  ; upgrade from a build without the uninstall UI) fall back to NSIS's dialog
  ; rather than failing.
  File \`/oname=$PLUGINSDIR\\index.min.html\` "${nsisString(inputs.uninstallHtmlPath!)}"

  StrCpy $UnStarted "0"
  StrCpy $UnHasUi "0"
  IfFileExists "$INSTDIR\\${UNINSTALL_RUNTIME_DIR}\\node.dll" 0 un_no_ui
    CopyFiles /SILENT "$INSTDIR\\${UNINSTALL_RUNTIME_DIR}\\node.dll" "$PLUGINSDIR\\node.dll"
    StrCpy $UnHasUi "1"
  un_no_ui:
FunctionEnd

UninstPage custom un.PageUi
UninstPage instfiles "" un.PageRemovePre
UninstPage custom un.PageDone

Function un.PageUi
  \${If} \${Silent}
    StrCpy $UnStarted "1"
    Return
  \${EndIf}
  \${If} $UnHasUi != "1"
    StrCpy $UnStarted "1"
    Return
  \${EndIf}

  ShowWindow $HWNDPARENT \${SW_HIDE}

  blinkkit::SetConfig /NOUNLOAD "productName" "\${PRODUCT_NAME}"
  blinkkit::SetConfig /NOUNLOAD "version" "\${PRODUCT_VERSION}"
  blinkkit::SetConfig /NOUNLOAD "publisher" "\${PRODUCT_PUBLISHER}"
  blinkkit::SetConfig /NOUNLOAD "exeName" "\${PRODUCT_EXE}"
  blinkkit::SetConfig /NOUNLOAD "installDir" "$INSTDIR"
  blinkkit::SetConfig /NOUNLOAD "mode" "uninstall"

  GetFunctionAddress $0 un.AbilityBeginUninstall
  blinkkit::RegisterAbility /NOUNLOAD "beginUninstall" $0
  GetFunctionAddress $0 un.AbilityCancel
  blinkkit::RegisterAbility /NOUNLOAD "cancel" $0

  ; Never full-screen: the splash is an arrival animation, and playing one to
  ; announce a removal would be odd.
  blinkkit::InitWindow /NOUNLOAD "$PLUGINSDIR" "\${PRODUCT_NAME}" "${c.window.width}" "${c.window.height}" "0"
  Pop $0
  \${If} $0 != "ok"
    ; The UI failed; do not strand the user with an uninstaller that does
    ; nothing. Continue with NSIS's own pages.
    StrCpy $UnStarted "1"
    StrCpy $UnHasUi "0"
    Return
  \${EndIf}

  blinkkit::ShowPage /NOUNLOAD

  \${If} $UnStarted != "1"
    Quit
  \${EndIf}
FunctionEnd

Function un.AbilityBeginUninstall
  StrCpy $UnStarted "1"
FunctionEnd

Function un.AbilityCancel
  Quit
FunctionEnd

Function un.PageRemovePre
  \${If} \${Silent}
    Return
  \${EndIf}
  \${If} $UnHasUi != "1"
    Return
  \${EndIf}
  ShowWindow $HWNDPARENT \${SW_HIDE}
  blinkkit::SetConfig /NOUNLOAD "mode" "uninstalling"
  blinkkit::BindProgress /NOUNLOAD
FunctionEnd

Function un.PageDone
  \${If} \${Silent}
    Return
  \${EndIf}
  \${If} $UnHasUi != "1"
    Return
  \${EndIf}
  blinkkit::SetConfig /NOUNLOAD "mode" "uninstalled"
  blinkkit::ShowPage /NOUNLOAD
FunctionEnd
`
    : ''
}
Section "Uninstall"
  SetShellVarContext ${shellContext}

  Delete "$DESKTOP\\${c.productName}.lnk"
  Delete "$SMPROGRAMS\\${startMenuFolder}\\${c.productName}.lnk"
  RMDir "$SMPROGRAMS\\${startMenuFolder}"

  ; The renderer is loaded from $PLUGINSDIR by now, not from $INSTDIR, so the
  ; parked copy is not locked and this succeeds.
  RMDir /r "$INSTDIR\\${UNINSTALL_RUNTIME_DIR}"
  RMDir /r "$INSTDIR"

  DeleteRegKey ${regRoot} "${uninstallKey}"
  DeleteRegKey ${regRoot} "${registryKey}"
SectionEnd
`;
}
